using ContentAuthoring.Shared;
using ContentAuthoring.Shared.HexWorld;
using System.IO;
using Xunit;

namespace ContentAuthoring.Shared.Tests;

public sealed class FactionFlagAuthoringTests
{
    [Fact]
    public void ShippedHexWorldsHaveValidControlAssets()
    {
        var baseGame = PackagePaths.FindDefaultBaseGame();
        Assert.False(string.IsNullOrEmpty(baseGame));
        var factions = StrategicFactionAuthoring.LoadStrategicFactions(
            StrategicFactionAuthoring.FactionDefaultFilePath(baseGame!));
        foreach (var name in new[] { "ch01_hex_world.json", "travel_mvp_hex_world_30x15.json" })
        {
            var world = HexWorldContentJson.LoadDefinition(Path.Combine(baseGame!, "Data", "Worlds", name));
            var errors = HexWorldContentValidator.Validate(world, factions).Where(i => i.Level == "error" &&
                (i.Message.Contains("FactionFlag") || i.Message.Contains("Control asset"))).ToList();
            Assert.True(errors.Count == 0, name + ": " + string.Join(" | ", errors.Select(e => e.Message)));
        }
    }

    [Fact]
    public void JsonRoundtripPreservesFlagsAndOrders()
    {
        var world = HexWorldContentGenerator.CreateBlank("test:world", "test", 20, 20, HexTerrainIds.Plain, true);
        world.Sites.Add(new HexWorldSiteDto { SiteId = "site:a", AnchorQ = 2, AnchorR = 2,
            Footprint = new() { new(2, 2) }, OwnerFactionId = "faction:a", ControlEstablishedOrder = 4 });
        world.FactionFlags.Add(new HexWorldFactionFlagDto { FlagId = "flag:a", FactionId = "faction:a",
            AnchorQ = 7, AnchorR = 7, EstablishedOrder = 9, HasLocalPosition = true, LocalX = 1.25f, LocalZ = -2.5f });

        var restored = HexWorldContentJson.LoadDefinition(HexWorldContentJson.Load(HexWorldContentJson.Serialize(world)));

        Assert.Equal(4, restored.Sites.Single().ControlEstablishedOrder);
        var flag = Assert.Single(restored.FactionFlags);
        Assert.Equal(9, flag.EstablishedOrder);
        Assert.True(flag.HasLocalPosition);
        Assert.Equal(1.25f, flag.LocalX);
        Assert.Equal(-2.5f, flag.LocalZ);
    }

    [Fact]
    public void DocumentCreatesAndDeletesFlagWithNextStableOrder()
    {
        var world = HexWorldContentGenerator.CreateBlank("test:world", "test", 20, 20, HexTerrainIds.Plain, true);
        world.Sites.Add(new HexWorldSiteDto { SiteId = "site:a", AnchorQ = 2, AnchorR = 2,
            Footprint = new() { new(2, 2) }, ControlEstablishedOrder = 3 });
        var doc = new HexWorldEditorDocument(); doc.Load(world, null);

        var flag = doc.CreateFactionFlag(new HexCoordDto(8, 8), "flag:a", "faction:a");

        Assert.True(flag.Success);
        Assert.NotNull(flag.Flag);
        Assert.Equal(4, flag.Flag!.EstablishedOrder);
        Assert.True(doc.DeleteFactionFlag("flag:a"));
        Assert.Empty(doc.World.FactionFlags);
    }

    [Fact]
    public void ValidatorWarnsForEnemyNominalOverlapButDoesNotRejectIt()
    {
        var world = HexWorldContentGenerator.CreateBlank("test:world", "test", 20, 20, HexTerrainIds.Plain, true);
        world.FactionFlags.Add(new HexWorldFactionFlagDto { FlagId = "flag:a", FactionId = "faction:a", AnchorQ = 8, AnchorR = 8, EstablishedOrder = 1 });
        world.FactionFlags.Add(new HexWorldFactionFlagDto { FlagId = "flag:b", FactionId = "faction:b", AnchorQ = 9, AnchorR = 8, EstablishedOrder = 2 });

        var issues = HexWorldContentValidator.Validate(world);

        Assert.Contains(issues, i => i.Level == "warn" && i.Message.Contains("nominal ranges overlap"));
        Assert.DoesNotContain(issues, i => i.Level == "error" && i.Message.Contains("overlap"));
    }

    [Fact]
    public void AutoGeneratedFlagIdsAreUniqueAndHexBased()
    {
        var world = HexWorldContentGenerator.CreateBlank("test:world", "test", 20, 20, HexTerrainIds.Plain, true);
        var doc = new HexWorldEditorDocument();
        doc.Load(world, null);

        var a = new HexCoordDto(8, 8);
        var b = new HexCoordDto(9, 9);
        var idA = FactionFlagAuthoringIdGenerator.Generate(doc.World, a);
        var ra = doc.CreateFactionFlag(a, idA, "faction:a");
        var idB = FactionFlagAuthoringIdGenerator.Generate(doc.World, b);
        var rb = doc.CreateFactionFlag(b, idB, "faction:a");

        Assert.True(ra.Success && rb.Success);
        Assert.Equal("base:flag_q8_r8", idA);
        Assert.Equal("base:flag_q9_r9", idB);
        Assert.NotEqual(idA, idB);
        Assert.Equal(2, doc.World.FactionFlags.Count);
    }

    [Fact]
    public void AutoIdGeneratorAppendsSuffixWhenStemCollides()
    {
        var world = HexWorldContentGenerator.CreateBlank("test:world", "test", 20, 20, HexTerrainIds.Plain, true);
        world.FactionFlags.Add(new HexWorldFactionFlagDto
        {
            FlagId = "base:flag_q9_r9", FactionId = "faction:a",
            AnchorQ = 3, AnchorR = 3, EstablishedOrder = 5,
        });
        var doc = new HexWorldEditorDocument();
        doc.Load(world, null);

        Assert.Equal("base:flag_q9_r9_2", FactionFlagAuthoringIdGenerator.Generate(doc.World, new HexCoordDto(9, 9)));
    }

    [Fact]
    public void CreateRejectsDuplicateFlagIdWithExistingAnchor()
    {
        var world = HexWorldContentGenerator.CreateBlank("test:world", "test", 20, 20, HexTerrainIds.Plain, true);
        var doc = new HexWorldEditorDocument();
        doc.Load(world, null);

        var first = doc.CreateFactionFlag(new HexCoordDto(8, 8), "base:flag_test", "faction:a");
        Assert.True(first.Success);

        var second = doc.CreateFactionFlag(new HexCoordDto(10, 10), "base:flag_test", "faction:b");
        Assert.False(second.Success);
        Assert.Contains("base:flag_test", second.Message);
        Assert.Contains("(8,8)", second.Message);
        Assert.Single(doc.World.FactionFlags); // 失败不写入 document、不产生脏数据
    }

    [Fact]
    public void CreateRejectsImpassableAnchorWithTerrainAndCoords()
    {
        var world = HexWorldContentGenerator.CreateBlank("test:world", "test", 20, 20, HexTerrainIds.Plain, true);
        var cell = world.Cells.First(c => c.Q == 8 && c.R == 8);
        cell.Terrain = HexTerrainIds.Mountain;
        cell.Passable = false;
        var doc = new HexWorldEditorDocument();
        doc.Load(world, null);

        var result = doc.CreateFactionFlag(new HexCoordDto(8, 8), "base:flag_q8_r8", "faction:a");
        Assert.False(result.Success);
        Assert.Contains("(8,8)", result.Message);
        Assert.Contains("Mountain", result.Message);
        Assert.Contains("Passable=false", result.Message);
        Assert.Empty(doc.World.FactionFlags);
    }

    [Fact]
    public void ValidatorEmitsSingleIssueForDuplicateFlagIdsWithAllAnchors()
    {
        var world = HexWorldContentGenerator.CreateBlank("test:world", "test", 20, 20, HexTerrainIds.Plain, true);
        world.FactionFlags.Add(new HexWorldFactionFlagDto { FlagId = "flag:dup", FactionId = "faction:a", AnchorQ = 2, AnchorR = 2, EstablishedOrder = 1 });
        world.FactionFlags.Add(new HexWorldFactionFlagDto { FlagId = "flag:dup", FactionId = "faction:b", AnchorQ = 4, AnchorR = 4, EstablishedOrder = 2 });
        world.FactionFlags.Add(new HexWorldFactionFlagDto { FlagId = "flag:dup", FactionId = "faction:a", AnchorQ = 6, AnchorR = 6, EstablishedOrder = 3 });

        var issues = HexWorldContentValidator.Validate(world);
        var dup = issues.Where(i => i.Message.Contains("Duplicate FactionFlag FlagId 'flag:dup'")).ToList();

        Assert.Single(dup);
        Assert.Contains("(2,2)", dup[0].Message);
        Assert.Contains("(4,4)", dup[0].Message);
        Assert.Contains("(6,6)", dup[0].Message);
    }
}
